#!/usr/bin/env bash
# shellcheck source=/dev/null

source "${HOME}/git/dot-scripts-templates/cfg/update"

source "${HOME}/git/dot-scripts-templates/cfg/zsh"
source "${HOME}/git/dot-scripts-templates/cfg/prompt"

source "${HOME}/git/dot-scripts-templates/cfg/alias"
source "${HOME}/git/dot-scripts-templates/cfg/utils"
source "${HOME}/git/dot-scripts-templates/cfg/locale"

source "${HOME}/.keyrc"
