#!/usr/bin/env zsh

export ZSH=~/.oh-my-zsh

ZSH_THEME=""
export UPDATE_ZSH_DAYS=7
DISABLE_UPDATE_PROMPT="true"

plugins=(
    alias-tips
    autoupdate
    brew
    common-aliases
    fast-syntax-highlighting
    npm
    zsh-autosuggestions
    zsh-nvm
)

source $ZSH/oh-my-zsh.sh
