#!/usr/bin/env bash
# shellcheck source=/dev/null

export ZSH="${HOME}/.oh-my-zsh"

export ZSH_THEME=""
export UPDATE_ZSH_DAYS=7
export DISABLE_UPDATE_PROMPT="true"

export plugins=(
    alias-tips
    autoupdate
    fast-syntax-highlighting
    zsh-autosuggestions
    zsh-nvm
)

source "${ZSH}/oh-my-zsh.sh"
