#!/usr/bin/env zsh

export ZSH=~/.oh-my-zsh

ZSH_THEME=""
export UPDATE_ZSH_DAYS=7
DISABLE_UPDATE_PROMPT="true"

plugins=(
    autoupdate
    fast-syntax-highlighting
    zsh-autosuggestions
    zsh-nvm
)

source $ZSH/oh-my-zsh.sh
