#!/usr/bin/env zsh
# shellcheck disable=SC2164

sudo sh -c 'echo 0 > /sys/class/leds/led1/brightness'
sudo sh -c 'echo 0 > /sys/class/leds/led0/brightness'

run() {
    cd ~/git/"$1"/
    git pull
    npm run setup
    npm run "$2"
}

run "magnet-co-parser" "server"

run "rpi-tools-cron" "start"
run "rpi-tools-bot" "start"

cd ~
