#!/usr/bin/env bash
# shellcheck source=/dev/null

export ZSH_DOT_MAD="${HOME}/git/dot-scripts-templates/zsh"

source "${ZSH_DOT_MAD}/env"

source "${ZSH_DOT_MAD}/path"
source "${ZSH_DOT_MAD}/update"

source "${ZSH_DOT_MAD}/omz"
source "${ZSH_DOT_MAD}/prompt"

source "${ZSH_DOT_MAD}/alias"
source "${ZSH_DOT_MAD}/utils"

source "${HOME}/.keyrc"
