#!/usr/bin/env zsh
# shellcheck disable=SC2154

alias hr="tput cols | pjs \"''.padEnd(_, '—')\""
alias bat="hr && bat"
alias del="rm -rfv"
alias els="exa -alF --group-directories-first --git"
alias dls="lsd -lA --group-dirs first --date relative --blocks permission,date,size,name"
alias ff="tree -i -f | grep"
alias tree="pwd && tree -aIC 'node_modules|.git' --dirsfirst --sort=name"

alias aptin="\${DOT_FOLDER_SCRIPTS}/apt.sh"
alias aptup="apt-get update && apt-get dist-upgrade && apt-get autoremove && apt-get clean"
alias aptups="sudo -- sh -c 'apt-get update && apt-get dist-upgrade && apt-get autoremove && apt-get clean'"

alias brewin="\${DOT_FOLDER_SCRIPTS}/brew.sh"
alias brewup="echo \"\${C_GREEN}brews installed:\${C_OFF}\" && brew list --formula && echo \"\${C_YELLOW}casks installed:\${C_OFF}\" && brew list --cask && brew update && brew upgrade && brew cleanup && brew doctor"

alias npmin="\${DOT_FOLDER_SCRIPTS}/npm.sh"
alias npmls="npm ls -g --depth=0 && npm outdated -g"
alias npmup="for i in \$(npm -g outdated --parseable --depth=0 | cut -d: -f4); do printf \"\n ✨ %s \n\" \"\$i\" && npm i -g \"\$i\"; done"

alias npmcl="npm ls -g --json | jq -r '.dependencies|keys-[\"npm\"]|join(\"\n\")' | xargs -t npm remove -g"

alias nvmup="nvm install node && npmin"
alias nvmin="nvm install \$(cat .nvmrc) && npmin"
alias nvmcl="del \$(ls -td \${NVM_DIR}/versions/node/* | tail -n +2) && del \${NVM_DIR}/.cache/bin"
alias nvmls="echo \"\${C_BLUE}npm current:\${C_OFF} v\$(npm -v)\" && echo \"\${C_MAGENTA}node current:\${C_OFF} \$(node -v)\" && echo \"\${C_MAGENTA}node remote:\${C_OFF} \$(nvm version-remote)\" && echo && nvm ls"

alias st="speed-cloudflare-cli"
alias stn="speed-test -v"
alias dst="dd if=/dev/zero of=./testfile.mad bs=8k count=30000 && del ./testfile.mad"

alias gs="git status -s"
alias ga="git add . && gs"
alias gp="git push"
alias gpl="git pull origin master --no-edit"
alias gplo="git pull origin \$(git branch | grep '\*' | cut -d' ' -f2-) --no-edit"
alias grh="git reset --hard"
alias gbd="git branch -D \$(git branch | grep -v \* | xargs -r)"

alias syncbb="git pull origin master --no-edit && git pull bb master --no-edit && git push origin master && git push bb master"

alias depup="gpl && ncu -u && npm run setup && ga && gce 'update deps' && gp"

alias dsc="find . -name '.DS_Store' -type f -exec rm -rfv {} \;"
alias sdock="defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type='spacer-tile';}' && killall Dock"
