#!/usr/bin/env bash
# shellcheck source=/dev/null

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="${HOME}/.oh-my-zsh"

export UPDATE_ZSH_DAYS=7
export DISABLE_UPDATE_PROMPT="true"

export ZSH_PLUGINS="${ZSH_CUSTOM}/plugins"
export ZSH_THEME="powerlevel10k/powerlevel10k"

export plugins=(
    autoupdate
    fast-syntax-highlighting
    zsh-autosuggestions
    zsh-better-npm-completion
    zsh-completions
    zsh-nvm
)

source "${ZSH}/oh-my-zsh.sh"
