#!/usr/bin/env zsh
# shellcheck source=/dev/null

export ZSH="${HOME}/.oh-my-zsh"

export UPDATE_ZSH_DAYS=30
export DISABLE_UPDATE_PROMPT="false"

export ZSH_THEME="powerlevel10k/powerlevel10k"

export plugins=(
    autoupdate
    command-not-found
    you-should-use
    zsh-autosuggestions
    zsh-better-npm-completion
    zsh-completions
    zsh-nvm
    zsh-syntax-highlighting
)

source "${ZSH}/oh-my-zsh.sh"
