#!/usr/bin/env bash

export PATH="${HOME}/.cargo/bin:${PATH}"

export PATH="/usr/local/bin:${PATH}"
export PATH="/usr/local/sbin:${PATH}"
export PATH="/usr/local/opt/curl/bin:${PATH}"

export PATH="/data/data/com.termux/files/usr/bin:${PATH}"
export PATH="/data/data/com.termux/files/usr/bin/applets:${PATH}"

fpath+=("${NVM_DIR}/versions/node/$(node -v)/lib/node_modules/pure-prompt/functions")
fpath+=("/data/data/com.termux/files/usr/lib/node_modules/pure-prompt/functions")
