#!/usr/bin/env bash

export PATH="${PATH}:${HOME}/.cargo/bin"
export PATH="${PATH}:${HOME}/.local/bin"

export PATH="${PATH}:/usr/local/bin"
export PATH="${PATH}:/usr/local/opt/curl/bin"

export PATH="${PATH}:/sbin"
export PATH="${PATH}:/usr/sbin"
export PATH="${PATH}:/usr/local/sbin"

export PATH="${PATH}:/data/data/com.termux/files/usr/bin"
export PATH="${PATH}:/data/data/com.termux/files/usr/bin/applets"
