#!/usr/bin/env zsh

export BAT_CONFIG_PATH="${DOT_FOLDER}/cfg/bat.conf"

export PATH="${HOME}/.cargo/bin:${PATH}"
export PATH="${HOME}/.local/bin:${PATH}"

export PATH="/usr/local/bin:${PATH}"
export PATH="/usr/local/opt/curl/bin:${PATH}"

export PATH="/sbin:${PATH}"
export PATH="/usr/sbin:${PATH}"
export PATH="/usr/local/sbin:${PATH}"

export PATH="/data/data/com.termux/files/usr/bin:${PATH}"
export PATH="/data/data/com.termux/files/usr/bin/applets:${PATH}"
