#!/usr/bin/env bash
# shellcheck disable=SC2116 disable=SC2191

C_OFF="\033[0m"
C_GREEN="\033[0;32m"
C_BLUE="\033[0;34m"
C_MAGENTA="\033[0;35m"

V_NODE_REMOTE=$(nvm version-remote)
ARIA_ARGS=(--file-allocation=falloc --max-connection-per-server=3 --max-concurrent-downloads=3 --split=3 --max-tries=120 --retry-wait=5 --continue --remote-time)

download() {
    aria2c "$@" "${ARIA_ARGS[@]}"
}

youtube() {
    youtube-dl -o "youtube-dl/%(uploader)s - %(title)s.%(ext)s" --add-metadata --embed-subs --external-downloader aria2c --external-downloader-args "$(echo "${ARIA_ARGS[@]}")" "$@"
}

gc() {
    gs && git commit -m "$(echo "$@")"
}

gch() {
    if [ -z "$*" ]; then
        echo "${C_GREEN}checkout to ${C_MAGENTA}master${C_OFF}"
        git checkout master
    else
        echo "${C_GREEN}checkout to branch ${C_BLUE}$*${C_OFF}"
        git checkout -b "$@" || git checkout "$@"
    fi
}

chpwd() {
    if [ -z "${SKIP_CHPWD}" ]; then
        exa -alF --group-directories-first --git
    fi

    if [ "${PWD}" != "${PREV_PWD}" ]; then
        PREV_PWD="${PWD}"

        if [ -e ".nvmrc" ]; then
            printf "\n"
            echo "${C_GREEN}nvmrc:${C_OFF} $(cat .nvmrc)"
        fi

        if [ -e "package.json" ]; then
            echo "${C_GREEN}node used:${C_OFF} $(node -v)"
            echo "${C_GREEN}node last:${C_OFF} ${V_NODE_REMOTE}"
        fi
    fi
}

zshup() {
    SKIP_CHPWD=true
    START_PWD=${PWD}

    cd "${ZSH_DOT_MAD}" || return
    git pull
    cd "${ZSH_CUSTOM}/themes/powerlevel10k" || return
    git pull
    cd "${START_PWD}" || return
    zsh

    unset SKIP_CHPWD
}

one() {
    npm run "$1" --target="${3:-stable}" --testcase="$2" --browserdebug --selenium
}
