#!/usr/bin/env zsh

if [ -n "${IS_RPI}" ]; then
    export SKIP_NVMRC=true
fi

if [ -n "${IS_TERMUX}" ]; then
    export SKIP_NVMRC=true
    export NO_SUDO=true
    export OPENSSL_DIR=${PREFIX}
fi

export C_OFF="\033[0m"
export C_GREEN="\033[0;32m"
export C_YELLOW="\033[0;33m"
export C_BLUE="\033[0;34m"
export C_MAGENTA="\033[0;35m"

export HOMEBREW_NO_ANALYTICS=1

export BAT_CONFIG_PATH="${DOT_FOLDER}/extra/bat.conf"

export PYENV_ROOT="${HOME}/.pyenv"
export PATH="${PYENV_ROOT}/bin:${PATH}"

export PATH="${HOME}/.cargo/bin:${PATH}"
export PATH="${HOME}/.local/bin:${PATH}"

export PATH="/usr/local/bin:${PATH}"
export PATH="/usr/local/opt/curl/bin:${PATH}"
export PATH="/usr/local/opt/findutils/libexec/gnubin:${PATH}"

export PATH="/sbin:${PATH}"
export PATH="/usr/sbin:${PATH}"
export PATH="/usr/local/sbin:${PATH}"

export PATH="/data/data/com.termux/files/usr/bin:${PATH}"
export PATH="/data/data/com.termux/files/usr/bin/applets:${PATH}"
